# Generated by Django 5.0.4 on 2025-02-05 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('photo_videography', 'photo_videography'), ('event_planners', 'event_planners'), ('catering', 'catering'), ('bride_groom_service', 'bride_groom_service'), ('decoration', 'decoration'), ('transportation', 'transportation'), ('venue_planners', 'venue_planners')], default='event_planners', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
