# Generated by Django 5.0.4 on 2025-02-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'service_type': 'event_planners'}, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='service_provider.serviceprovider'),
        ),
    ]
