# Generated by Django 5.0.4 on 2025-02-06 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_serviceprovider_service_type_and_more'),
        ('user', '0002_alter_venue_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(limit_choices_to={'service_type': 'transportation'}, on_delete=django.db.models.deletion.CASCADE, related_name='transport_services', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('A/C-Bus', 'A/C-Bus'), ('Non-A/C-Bus', 'Non-A/C-Bus'), ('Travaler', 'Traveler'), ('Permium-Cars', 'Permium-Cars')], max_length=20)),
                ('seats', models.CharField(choices=[('20', '20'), ('30', '30'), ('45', '45')], max_length=20)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.transportationservice')),
            ],
        ),
    ]
