# Generated by Django 5.0.4 on 2025-02-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_transportationservice_transportationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationservice',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
