# Generated by Django 5.0.4 on 2025-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_bookevent_our_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='our_service',
            field=models.CharField(choices=[('Venue', 'Venue'), ('Transportation', 'Transportation'), ('Catering', 'Catering'), ('Decorations', 'Decorations'), ('BridalGroom', 'BridalGroom'), ('Photography', 'Photography')], max_length=50),
        ),
    ]
