# Generated by Django 5.0.4 on 2025-02-06 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_serviceprovider_service_type_and_more'),
        ('user', '0009_alter_bookevent_our_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(limit_choices_to={'service_type': 'catering'}, on_delete=django.db.models.deletion.CASCADE, related_name='catering_services', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CateringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cateringservice')),
            ],
        ),
    ]
