# Generated by Django 5.0.4 on 2025-02-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_decorationsservice_decorationsbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationsservice',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decorationsservice',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
