# Generated by Django 5.0.4 on 2025-02-07 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_serviceprovider_service_type_and_more'),
        ('user', '0013_decorationsbooking_custom_service_photographyservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridalGroomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('package_details', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(limit_choices_to={'service_type': 'bride_groom_service'}, on_delete=django.db.models.deletion.CASCADE, related_name='bridal_groom_services', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='BridalGroomServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('suggest_theme', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bridalgroomservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
