# Generated by Django 5.0.4 on 2025-02-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_serviceprovider_service_type_and_more'),
        ('user', '0015_remove_event_itinerary_bookevent_customize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographyservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photography_services', to='service_provider.serviceprovider'),
        ),
    ]
